### ISSUE TITLE
Solve npm/npm#13306 in gitlab-ci-runner-java-node image

### ISSUE THREAD

**Issue by pandres95** [peterreisz/docker-containers#1]
Can you please apply the solution proposed [here](https://github.com/npm/npm/issues/13306#issuecomment-236876133) while building the docker image?

**Comment by peterreisz** [comment]
I've published a new image to the docker hub, but it's a little bit different.
Clean node+java8 and no globally installed node packeges and java build tools.
All versions are upgraded, even the gitlab runner. Is it OK for you?

**Comment by pandres95** [comment]
It's perfect! Thanks.
